### ISSUE TITLE
Screen resize issues in Horizon VDI environment

### ISSUE THREAD

**Issue by carterscottm** [flameshot-org/flameshot-org.github.io#137] opened 2023-10-09 15:01 UTC
At work I administer our VMware Horizon VDI environment.  I use Flameshot in my VDI instance (Windows 11 22H2) while in the office, and I use a 36" monitor and a 27" monitor there.  At home I use two 27" monitors to connect to the same VDI instance.  I also use a linux-based laptop when travelling (without a second display), and connect into VDI through that machine as well.  Horizon client is configured to use the full screen in all cases.  When switching between locations without rebooting my VM, I have to close and restart my flameshot app in order for it to recognize the difference in screen size.  This is only a problem when moving from a smaller display to larger displays since flameshot is only aware of a portion of the screen geometry.

A possible workaround/fix would be for Flameshot to detect changes in screen geometry during any of the following events after launch:

- User login/unlock
- Semi-frequent schedule (every five minutes or so)
- Each time it's called to take a screenshot

**Comment by mmahmoudian** [comment] 2023-10-09 20:26
@carterscottm 

Thanks for taking the time to report a bug.

> I have to close and restart my flameshot app in order for it to recognize the difference in screen size.

Yes, we are aware of the issue. It has been reported in various ways and context. For example:
- https://github.com/flameshot-org/flameshot/issues/3320
- https://github.com/flameshot-org/flameshot/issues/2610

The fix would be to run the monitor detection again after the trigger and right before requesting the screenshot from the operating system/compositor/... .

I will close this issue for two reasons:
1. It is duplicate of the ones I listed above
2. you have posted this in the repository of our website and not the software. Please consider opening issues in the [other repository](https://github.com/flameshot-org/flameshot/issues) is the bug is related to the software.
3. It is not in the bug report format and lacks essential information (Flameshot version, installation method, ...)

**Closed by mmahmoudian** 2023-10-09 20:26 UTC
